# Generated by Django 2.2.6 on 2019-11-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_auto_20191112_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.BooleanField(default=False, verbose_name='finalizado'),
        ),
    ]
