# Generated by Django 2.2.6 on 2019-11-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_auto_20191112_0143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['data_de_criacao']},
        ),
    ]
