# Generated by Django 2.2.6 on 2019-11-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_auto_20191112_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_de_execucao',
            field=models.DateTimeField(auto_now=True, verbose_name='data de execução'),
        ),
    ]
